export enum StringID {
  HEADER_TITLE = 'HEADER_TITLE',
  ARTICLE_LIST_NEW_ARTICLE = 'ARTICLE_LIST_NEW_ARTICLE',
  EDIT_ARTICLE_TOPIC = 'EDIT_ARTICLE_TOPIC',
  EDIT_ARTICLE_TITLE = 'EDIT_ARTICLE_TITLE',
  EDIT_ARTICLE_BODY = 'EDIT_ARTICLE_BODY',
  EDIT_ARTICLE_SUBMIT = 'EDIT_ARTICLE_SUBMIT',
  INPUT_COMMENT_SUBMIT = 'INPUT_COMMENT_SUBMIT',
  ACTION_LIKE = 'ACTION_LIKE',
  ACTION_DISLIKE = 'ACTION_DISLIKE',
}
